name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # ... other options
          base: header, community, activity, repositories, metadata         # Only display "header" and "repositories" sections
          repositories: 100                                                 # Query only last 100 repositories
          repositories_batch: 25                                            # Query repositories 25 by 25 (lower this to avoid API timeouts)
          repositories_forks: no                                            # Don't include forks
          repositories_affiliations: owner, collaborator                    # Display only repositories where user is owner or collaborator
          repositories_skipped: lowlighter/lowlighter                       # Exclude automatically "lowlighter/lowlighter" repository from plugins allowing a skip list
          commits_authoring: Hotklou2404                                    # Handle you use when authoring commits, which can be used to filter commits in other plugins
          plugin_achievements: yes
          plugin_achievements_threshold: B                                  # Display achievements with rank B or higher
          plugin_achievements_secrets: yes                                  # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut                             # Hide octonaut achievement
          plugin_achievements_limit: 0                                      # Display all unlocked achievement matching threshold and secrets params
          plugin_achievements_display: compact                              # Use compact display
