name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # ... other options
          # Only display "header" and "repositories" sections
          base: header, community, activity, repositories, metadata
          # Query only last 100 repositories
          repositories: 100
          # Query repositories 25 by 25 (lower this to avoid API timeouts)
          repositories_batch: 25
          # Don't include forks
          repositories_forks: no
          # Display only repositories where user is owner or collaborator
          repositories_affiliations: owner, collaborator
          # Exclude automatically these repositories from plugins allowing a skip list
          repositories_skipped: lowlighter/lowlighter
          # Enable Lines plugin
          plugin_lines: yes
          # List of skipped repositories
          plugin_lines_skipped: repo
          # Handle you use when authoring commits, which can be used to filter commits in other plugins
          commits_authoring: Hotklou2404
          # Set your timezone
          config_timezone: Africa/Johannesburg
          # Set the amount of times that the rendering of the metrics can be retried
          retries: 3
          # Set the delay between metric rendering retries
          retries_delay: 300
          # Enable Achievemnts plugin
          plugin_achievements: yes
          # Display achievements with this rank or higher
          plugin_achievements_threshold: B
          # Display unlocked secrets achievements
          plugin_achievements_secrets: yes
          # Hide octonaut achievement
          plugin_achievements_ignored: octonaut
          # Display all unlocked achievement matching threshold and secrets params
          plugin_achievements_limit: 0
          # Display mode
          plugin_achievements_display: detailed
          # Enable Languages plugin
          plugin_languages: yes
          # List of languages to ignore
          plugin_languages_ignored: html, css
          # List of repositories to skip
          plugin_languages_skipped: my-test-repo
          # Display up to 8 languages
          plugin_languages_limit: 12
          # Display most used and recently used
          plugin_languages_sections: most-used, recently-used
          # Make most used languages and other specified languages a different colour
          # plugin_languages_colors: "0:orange, javascript:#ff0000, ..."
          # Customize languages names with aliases
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..."
          # Additionally display total bytes size and percentage
          plugin_languages_details: bytes-size, percentage
          # Hides all languages less than 2%
          plugin_languages_threshold: 2%
          # Get indepth stats (see documentation before enabling)
          plugin_languages_indepth: no
          # Set maximum time for indepth analysis
          plugin_languages_analysis_timeout: 15
          # Display only languages that match these categories in most-used section
          plugin_languages_categories: programming
          # Display only languages that match these categories in recently-used section
          plugin_languages_recent_categories: markup, programming, data
          # Load up to this amount of events to compute recently used stats
          plugin_languages_recent_load: 1000
          # Limit recently used stats to this amount of days
          plugin_languages_recent_days: 30
          # Enable Habits plugin
          plugin_habits: yes
          # Use 200 events to compute habits
          plugin_habits_from: 1000
          # Keep only events from last 30 days
          plugin_habits_days: 30
          # Display facts section
          plugin_habits_facts: yes
          # Display charts section
          plugin_habits_charts: yes
          # Trim unused hours on daily chart
          plugin_habits_trim: no
          # Enable Licenses plugin
          plugin_licenses: yes
          # Command to setup target repository
          plugin_licenses_setup: npm ci
          # Display used licenses ratio
          plugin_licenses_ratio: yes
          # Display permissions, limitations and conditions
          plugin_licenses_legal: yes
          # Enable Followup plugin
          plugin_followup: yes
          # Display overall status of issues/pull requests created on user's repositories and created by user
          plugin_followup_sections: repositories, user
          # Enable Traffic plugin
          plugin_traffic: yes
          # Enable Isocalendar plugin
          plugin_isocalendar: yes
          # Display full year instead of half year
          plugin_isocalendar_duration: full-year
          # Enable Activity plugin
          plugin_activity: yes
          # Limit to 5 events
          plugin_activity_limit: 10
          # Load up to 100 recent events from API (should be higher than "limit")
          plugin_activity_load: 1000
          # Keep only events from last 14 days (set to 0 for no limit)
          plugin_activity_days: 30
          # Show all events (use table above to filter events types)
          plugin_activity_filter: all
          # Only display public events
          plugin_activity_visibility: public
          # Display events timestamps
          plugin_activity_timestamps: yes
          # Ignored repositories
          plugin_activity_skipped: repo
